### PR TITLE
Languages list / Query search / More data on subtitles / Error management on callback

### PR DESCRIPTION
**Pull request by iGranDav**
This pull request added several improvements that we used on our app:

* get languages list
* query search (usefull if hash search returns nothing)
* add more metas on subtitles
* call callbacks with errors in case of errors (allow UI feedback)

### CODE REVIEW

**Comment by orta** [comment]
aww, can't be merged!
I would totally do so.

**Comment by iGranDav** [comment]
:/ I don't see the conflict here

**Comment by orta** [comment]
screen shot 2015-02-26 at 22 30 27

**Comment by iGranDav** [comment]
Yes I saw this problem, but unfortunatly you need to merge those conflicts manually yourself since I have no write access to your repository.

**Comment by orta** [comment]
`git pull upstream master` - the idea is that we've both made changes to the same file, if you pull those changes then amend and push it fixes it.

**Comment by iGranDav** [comment]
@orta forgot about this sorry... You should be able to merge this one now 😊

PS: Will pushing a new one with tvOS compatibility

**Comment by orta** [comment]
Ace no worries, I'll add you as a repo owner, you're welcome to submit PRs, but I trust you know what your doing too

**Pull request merged**
